// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('d:/Projects/ReactProjects/DiabetesJournal/node_modules/react');
var { Component } = React;
var ReactNative = require('d:/Projects/ReactProjects/DiabetesJournal/node_modules/react-native');
var { AppRegistry } = ReactNative;
var entryPoint = require('d:/Projects/ReactProjects/DiabetesJournal/index.ios.js');
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('DiabetesJournal', appParameters);
});